name: make_ufo

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  launch_ufo:
    runs-on: windows-latest

    steps:

    - uses: actions/cache@v4
      with:
        path: D:\a\stellarium
        key: cache-0
        restore-keys: cache

    - uses: actions/checkout@v5

    - uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.3.*'
        version: '6.8.3'
        host: 'windows'
        target: 'desktop'
        cache: true
        arch: 'win64_msvc2022_64'
        modules: 'qtcharts qtimageformats qtlocation qtmultimedia qtpositioning qtscxml qtsensors qtserialbus qtserialport qtvirtualkeyboard qtwebchannel qtwebengine qtwebsockets qtwebview debug_info qt5compat qtquicktimeline qtshadertools'

    - env: 
        CMAKE_PREFIX_PATH: ${{env.QT_ROOT_DIR}}
      run: cmake -B build -S "${{ github.workspace }}" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSTELLARIUM_RELEASE_BUILD=Off -DENABLE_TESTING=On -DCMAKE_INSTALL_PREFIX=stellarium-bin -DSCM_SHOULD_ENABLE_CONVERTER=OFF -G "Visual Studio 17 2022" -A x64

    #- run: cmake --build build --config RelWithDebInfo -j ${{env.parallel_processes}} --target install
    
    - run: ls ./../
        
